apiVersion: apps/v1
kind: Deployment
metadata:
  name: miko-assignment-sb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miko-assignment-sb1
  template:
    metadata:
      labels:
        app: miko-assignment-sb1
    spec:
      containers:
        - name: miko-assignment-sb1
          image: miko-assignment-sb-docker1:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: miko-assignment-sb-service
spec:
  selector:
    app: miko-assignment-sb1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
        - name: redis-server
          image: redis:latest
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis-server
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
        - name: redis-insight
          image: redislabs/redisinsight:latest
          env:
            - name: REDIS_URI
              value: "redis://redis-service:6379"
          ports:
            - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: redis-insight-service
spec:
  selector:
    app: redis-insight
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-insight-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
